spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  datasource:
    url: jdbc:postgresql:///auth_db?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: n11user
    password: ${DB_USER_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000
      keepalive-time: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

feign:
  user-service:
    url: https://user-service-693501117153.europe-west1.run.app
