server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
