server:
  port: 8080
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
  datasource:
    url: jdbc:postgresql:///payment_db?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: n11user
    password: ${DB_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      auto-startup: false
      missing-topics-fatal: false
    admin:
      fail-fast: false
      auto-create: false
    producer:
      properties:
        max.block.ms: 5000
        delivery.timeout.ms: 10000
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
