server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql:///payment_db?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: n11user
    password: ${DB_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: health
