server:
  port: 9095

spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:caglar}
    password: ${POSTGRES_PASSWORD:root}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/paymentdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

app:
  security:
    mode: open

iyzico:
  api-key:          ${IYZICO_API_KEY:sandbox-6WzXl3t6CTSwQlQ5WWmvom7N64Wjo1tR}
  secret-key:       ${IYZICO_SECRET_KEY:sandbox-DbJPjQdBHRHTd3rpUCnAPqfzBcP6LeAh}
  base-url:         ${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}
  callback-url:     ${IYZICO_CALLBACK_URL:http://localhost:9095/dev/v1/payment/iyzico/callback}
  success-redirect: ${IYZICO_SUCCESS_REDIRECT:http://localhost:3000/orders/{orderId}/result}
  failure-redirect: ${IYZICO_FAILURE_REDIRECT:http://localhost:3000/orders/{orderId}/result}

openapi:
  title: Payment Service API
  version: v1
  description: İyzico ödeme akışı

management:
  endpoints:
    web:
      exposure:
        include: health,info
