server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGO_DB_NAME:user_db}
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

feign:
  auth-service:
    url: https://auth-service-693501117153.europe-west1.run.app
