server:
  port: 8080
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
