server:
  port: 9093

spring:
  application:
    name: basket-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  security:
    mode: downstream

basket:
  ttl-seconds: 86400  # 1 gün

openapi:
  title: Basket Service API
  version: v1
  description: Sepet (Redis) işlemleri

management:
  endpoints:
    web:
      exposure:
        include: health,info
